Disambiguate hedgehog test filename to fix error
Previously, `cabal test` would error because of a strange interaction
between the filename `hedgehog.hs`, the inferred module name `Hedgehog`
and the existing `Hedgehog` library import:

```
test/Hedgehog.hs:1:1: error:
    File name does not match module name:
    Saw: ‘Main’
    Expected: ‘Hedgehog’
```

I resolved this by renaming the file to `hedgehog_tests.hs`.  I also
renamed the other tests for consistency.